# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0009_auto_20170824_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='info',
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date photo was uploaded.'),
        ),
    ]
