# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 22:33
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0010_auto_20170827_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='info',
            field=jsonfield.fields.JSONField(null=True, verbose_name='Meta data about the image, usually from the EXIF Header'),
        ),
    ]
